export const AUTH_ERROR_CODES = {
  PASSWORD_MISMATCH: 'AUTH-001',
  EMAIL_ALREADY_EXISTS: 'AUTH-002',
  USER_NOT_FOUND: 'AUTH-003',
  INVALID_CREDENTIALS: 'AUTH-004',
  SESSION_NOT_FOUND: 'AUTH-005',
  SESSION_REVOKED: 'AUTH-006',
  SESSION_EXPIRED: 'AUTH-007',
  INVALID_REFRESH_TOKEN: 'AUTH-008',
  MAX_SESSIONS_EXCEEDED: 'AUTH-009',
} as const;
